version: '3.8'

services:
  cache:
    container_name: redis
    image: redis:alpine
    restart: always
    ports:
      - ${REDIS_MAP_PORT:-6379 }:${REDIS_EXPOSE_PORT:-6379}
    volumes:
      - cache:/data
    networks:
      - eververse-local

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${MAP_PORT:-80}:${EXPOSE_PORT:-1323}
    networks:
      - eververse-local

networks:
  eververse-local:
    external: true

volumes:
  cache:
    driver: local
