version: '3.8'

services:
  cache:
    container_name: redis-service
    image: redis:alpine
    restart: always
    ports:
      - ${REDIS_PORT:-6379 }:${REDIS_PORT:-6379}
    volumes:
      - cache:/data
    networks:
      - eververse-local

  web:
    container_name: web
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT:-8080}:${SERVER_PORT:-1323}
    networks:
      - eververse-local

networks:
  eververse-local:
    external: true

volumes:
  cache:
    driver: local
